Тестирование проекта со второго семестра
AlexKhochenkov/homework-1-autumn-2024 pull request #1
Opened 2024-09-22 14:01 UTC by Karpov-Ivan

2024-09-23 19:58 UTC, Karpov-Ivan commented on MailHub.md
> +* При нажатии на кнопку "Удалить" происходит удаление папки, при этом пользователь остаётся на той же странице, на которой был
Я думаю стоит рассмотреть случай, когда ты на вкладке папки и её удаляешь. Куда ты перенаправляешься надо бы описать.

2024-09-23 19:59 UTC, Karpov-Ivan commented on MailHub.md
> +## Кнопки для "основных" папок
Добавь здесь, что на кнопках отображается число непрочитанных чисел

2024-09-23 20:00 UTC, Karpov-Ivan commented on MailHub.md
> +* Если папок нет или письмо уже находится в единственно созданной папке, то выпадает надпись "Нет папок!"
А если уже добавлен в какую-то папку, то этот список не выводится

2024-09-23 20:04 UTC, Karpov-Ivan commented on MailHub.md
> +* В списке писем отображаются письма из разных категорий: Входящие, Отправленные, Черновики, Спам, письма из папок
Пришлось задуматься над формулировкой немного)

2024-09-23 20:06 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие вне кнопок Отметить прочитанным/непрочитанным, Выбрать письмо открывает письмо, т.е. происходит перенаправление на https://mailhub.su/letter?id={letter_id}
Возьми в кавычки кнопки, а то плохо читается

2024-09-23 20:07 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие меняет отображение статуса прочтения (с прочитанного на непрочитанный и обратно) и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/email/update/{letter_id}
Наверное нужно указать, что сначала выделяем письмо. И убери запрос на бекенд лучше.

2024-09-23 20:09 UTC, Karpov-Ivan commented on MailHub.md
> +* Содержит счетчик выбранных письем
Опечатка

2024-09-23 20:10 UTC, Karpov-Ivan commented on MailHub.md
> +*  Нажатие меняет отображение статуса прочтения (с прочитанного на непрочитанный и обратно) у всех писем для Отметить все прочитанными и у выбранных писем для Пометить прочитанными/Пометить непрочита
Убери про бекенд и бери в кавычки кнопки, плохо читается

2024-09-23 20:11 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие убирает выбранные письма из списка писем, с последующими изменениями интерфейса (меняется счетчик писем, перерендер тулбара) и отправляет запрос на бэкенд по API  https://mailhub.su/api/v1/
Убери про бекенд

2024-09-23 20:12 UTC, Karpov-Ivan commented on MailHub.md
> +* Последующий выбор папки выполняет редирект на https://mailhub.su/folder?{folder_id} и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/folder/add_email
Убери про бекенд

2024-09-23 20:12 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие убирает письмо из списка писем в папке и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/folder/delete_email
Убери про бекенд

2024-09-23 20:12 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие убирает письмо из текущего списка писем и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/email/update/{letter_id}
Убери про бекенд

2024-09-23 20:13 UTC, Karpov-Ivan commented on MailHub.md
> +* В контейнере письма отображается вся доступна пользователю информация о письме: статус прочтения, отправитель, аватар отправителя, тема, текст, дата отправления, вложения. В случае отображения спис
Опечатка есть

2024-09-23 20:14 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие меняет отображение статуса прочтения (с прочитанного на непрочитанный и обратно) и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/email/update/{letter_id}
Убери про бекенд

2024-09-23 20:15 UTC, Karpov-Ivan commented on MailHub.md
> +### Кнопка "Посмотреть вложения"
Возможно стоит упомянуть форматы вложений, но я в этом неуверен

2024-09-23 20:16 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие выполняет редирект на https://mailhub.su/main и отправляет запрос на бэкенд по API  https://mailhub.su/api/v1/email/delete/{letter_id}
Убери про бекенд

2024-09-23 20:16 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие выполняет редирект на https://mailhub.su/folder?{folder_id} и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/folder/delete_email
Убери про бекенд

2024-09-23 20:16 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие выполняет редирект на https://mailhub.su/main и отправляет запрос на бэкенд по API https://mailhub.su/api/v1/email/update/{letter_id}
Убери про бекенд

2024-10-01 09:51 UTC, Fedasov approved these changes

2024-10-01 11:52 UTC, AlexKhochenkov approved these changes

2024-10-01 12:19 UTC, Karpov-Ivan commented on MailHub.md
> +*  Нажатие меняет отображение статуса прочтения (с прочитанного на непрочитанный и обратно)  и отправляет запросы на бэкенд по от API https://mailhub.su/api/v1/email/update/{letter_id}
Убери про бекенд

2024-10-01 12:19 UTC, Karpov-Ivan commented on MailHub.md
> +### Общее
Забыл про кнопку в "В папку"

2024-10-01 12:19 UTC, Karpov-Ivan commented on MailHub.md
> +* Нажатие выполняет редирект https://mailhub.su/login и отправляет запросы на бэкенд по от API https://mailhub.su/api/v1/auth/logout
Убери бекенд)

2024-10-01 12:19 UTC, Karpov-Ivan commented on MailHub.md
> +* В случае, если поле "Кому" содержит что либо кроме латинских букв, цифр и сиволов '_','.','+','-','%' в левой части адреса, то выдается ошибка "Некорректное имя ящика получателя".
Символы обознач получше

2024-10-01 12:19 UTC, Karpov-Ivan commented on MailHub.md
> +## Прикрепление файла к письму
Укажи какие форматы можно прикрепить

2024-10-01 18:36 UTC, Karpov-Ivan reviewed
аппрув

2024-10-01 18:46 UTC, frelikhmax approved these changes

2024-10-01 18:59 UTC, frelikhmax commented on MailHub.md
> +### Общее
такой нет на странице письма

2024-10-03 16:16 UTC, BeeHeather requested changes
Привет! Посмотрела pr, основные моменты:
- Добавьте скрины к проверкам
- Добавьте проверку разделов авторизации и регистрации 
- Некоторые тесты нужно декомпозировать

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При вводе небольшого количества символов в названии папки надпись корректно отображается
Небольшого - это какого? Есть ли минимально допустимое количество символов у названия папки? Если да - добавьте соответствующую проверку

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При достаточно длинном названии папки часть названия скрывается
Здесь тоже укажите конкретное количество символов (либо можно привести конкретный пример названия, который будете использовать при тесте), и добавьте скрин

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +## Общее
Здесь замечания аналогичны разделу про создание папки

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Если пользователь находится на странице писем данной папки, то при удалении пользователь остается на той же странице
Чем этот кейс отличается от предыдущего?

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Если папок нет или письмо уже находится в единственно созданной папке, то выпадает надпись "Нет папок!"
Кмк можно разделить на две проверки

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +## Кнопка "Убрать из папки"
В какой из проверок мы проверяем, что письмо удалилось из папки?

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* В случае если поля "Фамилия" и "Имя" и "Отчество" не пустые, но содержат что-либо кроме букв латиницы, кириллицы выдается ошибка "Некорректная фамилия" или "Некорректное имя" или "Некорректное отче
Добавьте проверку на граничные значения количества символов в каждом из полей

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* В случае если поле "О себе" не пустое, то может содержать любые символы.
Переформулируйте пункт, или вместо "то" напишите "оно"

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При нажатии на кнопку "Сохранить" происходит замена текста в кнопке на "Успешно сохранено", данные сохраняются или указываются ошибки.
"или указываются ошибки" - это уже другая проверка, добавьте ее отдельно

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При нажатии на кнопку "Удалить ящик" всплывает плашка "Вы уверены, что хотите удалить ящик?", чтобы пользователь подтвердил действие. Если пользователь подтверждает, то удаляется профиль пользовате
А если пользователь не подтвердит действие? И добавьте скрин

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При нажатии на аватарку/плейсхолдер отображается окно изменения аватара
Разделите на две отдельных проверки

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При сохранении изображения с поддерживаемыми типами (`.jpg`, `.jpeg`, `.jfif`, `.pjpeg`, `.pjp`, ``.png`) и весом более 5МБ аватар не обновляется, под аватаром отображается предупреждение о том, чт
Выглядит как баг, мб здесь стоило бы выводить ошибку "Изображение весит более 5МБ"

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +## Окно изменения аватара
Добавьте проверку на попытку загрузки файла неподдерживаемого типа, и на успешную загрузку фото

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Информация, которую можно узнать о письмах в списке писем: статус прочтения, отправитель, аватар отправителя, тема, текст, дата отправления. В случае отображения списка отправленных, отправитель и
Список отправленных давайте в отдельную проверку вынесем

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Отправитель, тема, текст у писем из списка писем могут отображаться не полностью
В каком случае?

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Через список писем можно выбрать нужное письмо и выполнить с ним следующие действия: открыть письмо, отметить прочитанных/непрочитанным, выбрать
Го в этой проверке проверим наличие кнопок действий в опциональном меню письма (перефразируйте проверку)

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Список писем загружается и рендерится полностью, независимо от количества писем в нем
Какое количество писем вы будете здесь проверять?

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Позволяет производить манипуляции с выбранными письмами
Это можно убрать, мы на каждую кнопку пишем отдельный тест

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Позволяет производить манипуляции со всеми письмами из списка
Аналогично предыдущему

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* В контейнере письма отображается вся доступна пользователю информация о письме: статус прочтения, отправитель, аватар отправителя, тема, текст, дата отправления, вложения. В случае отображения спис
Да, опечатку поправьте в слове "соответсвенно"

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* Ошибка выводится под полем в формате "Некорректная [название поля]" или "Некорректное [название поля]" или "Некорректный [название поля]".
Можно не выносить это в отдельный тест

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При нажатии на кнопку "Отправить" письмо со всеми полями и файлами сохраняется, отправляется на указанный адрес и происходит переход на [вкладку "Входящие"](https://mailhub.su/main) или указываются
"или указываются ошибки" - это отдельная проверка

2024-10-03 16:16 UTC, BeeHeather commented on MailHub.md
> +* При сохранении файла весом более 20МБ файл не прикрепляется, под кнопкой отображается ошибка "Файл превышает максимальный размер 20 МБ".
Файл может быть любого расширения? Если нет, добавьте соответствующую проверку

2024-10-04 17:53 UTC, Fedasov commented on MailHub.md
> +* При вводе небольшого количества символов в названии папки надпись корректно отображается
Минимально допустимое количество символов нет, здесь имеется ввиду что по длине не помещается.
Пользователь может ввести следующие названия с разным количеством символов, но одинаковой длиной:
1) fffffffffffff
2) wwwwww

2024-10-04 17:54 UTC, Fedasov commented on MailHub.md
> +* При достаточно длинном названии папки часть названия скрывается
Здесь тоже самое:
1) fffffffffffff..
2) wwwwww..

2024-10-05 07:17 UTC, AlexKhochenkov commented on MailHub.md
> +* В случае, если поле "Кому" содержит что либо кроме латинских букв, цифр и сиволов '_','.','+','-','%' в левой части адреса, то выдается ошибка "Некорректное имя ящика получателя".
Получше это как?

2024-10-06 07:32 UTC, Karpov-Ivan commented on MailHub.md
> +* В случае если поля "Фамилия" и "Имя" и "Отчество" не пустые, но содержат что-либо кроме букв латиницы, кириллицы выдается ошибка "Некорректная фамилия" или "Некорректное имя" или "Некорректное отче
Добавил

2024-10-06 07:33 UTC, Karpov-Ivan commented on MailHub.md
> +* В случае если поле "О себе" не пустое, то может содержать любые символы.
Переформулировал

2024-10-06 07:36 UTC, Karpov-Ivan commented on MailHub.md
> +* При нажатии на кнопку "Сохранить" происходит замена текста в кнопке на "Успешно сохранено", данные сохраняются или указываются ошибки.
Добавил

2024-10-06 07:42 UTC, Karpov-Ivan commented on MailHub.md
> +* При нажатии на кнопку "Удалить ящик" всплывает плашка "Вы уверены, что хотите удалить ящик?", чтобы пользователь подтвердил действие. Если пользователь подтверждает, то удаляется профиль пользовате
Добавил

2024-10-06 07:47 UTC, Karpov-Ivan commented on MailHub.md
> +* При нажатии на аватарку/плейсхолдер отображается окно изменения аватара
Плейсхолдера оказывается нет, но есть кнопка. Сделал для кнопки

2024-10-06 07:51 UTC, Karpov-Ivan commented on MailHub.md
> +* При сохранении изображения с поддерживаемыми типами (`.jpg`, `.jpeg`, `.jfif`, `.pjpeg`, `.pjp`, ``.png`) и весом более 5МБ аватар не обновляется, под аватаром отображается предупреждение о том, чт
Я допустил ошибку, там на самом деле выводится "Файл превышает максимальный размер 5 МБ". Исправил

2024-10-06 08:01 UTC, Karpov-Ivan commented on MailHub.md
> +## Окно изменения аватара
Вообще, чтобы загрузить файл другого типа, придётся в панели разработчика убрать в html разрешение. Но я это сделал и там ошибка у нас выдаётся. Всё добавил.

2024-10-06 09:34 UTC, Fedasov commented on MailHub.md
> +* Если пользователь находится на странице писем данной папки, то при удалении пользователь остается на той же странице
1) Пользователь удаляет папку в каком угодно месте, только не на странице писем данной папки,
2) Пользователь находится на странице писем данной папки и удаляет эту папку.

2024-10-06 09:44 UTC, Fedasov commented on MailHub.md
> +## Кнопка "Убрать из папки"
"Убрать из папки" здесь же и проверяем

2024-10-06 09:45 UTC, Fedasov commented on MailHub.md
> +* Если папок нет или письмо уже находится в единственно созданной папке, то выпадает надпись "Нет папок!"
Есть же разделение на две проверки:
1) Добавление письма в папку
2) Удаление письма из папки
Или я не так тебя понял?

2024-10-06 13:29 UTC, frelikhmax commented on MailHub.md
> +* Через список писем можно выбрать нужное письмо и выполнить с ним следующие действия: открыть письмо, отметить прочитанных/непрочитанным, выбрать
что такое опциональное меню? нет кнопки действия для открытия письма, оно открывается только по клику на контейнер письма в списке

2024-10-06 13:33 UTC, frelikhmax commented on MailHub.md
> +* При сохранении файла весом более 20МБ файл не прикрепляется, под кнопкой отображается ошибка "Файл превышает максимальный размер 20 МБ".
любого

2024-10-06 18:03 UTC, Fedasov commented on MailHub.md
> +* Если папок нет или письмо уже находится в единственно созданной папке, то выпадает надпись "Нет папок!"
Разделил на две проверки

2024-10-08 15:30 UTC, BeeHeather requested changes
Привет! Допишите плиз тесты на разделы авторизации и регистрации, не увидела их в этом pr

2024-10-08 15:30 UTC, BeeHeather commented on MailHub.md
> +* При вводе небольшого количества символов в названии папки надпись корректно отображается
Закиньте пример в проверку - можно в скобках (fffffffffffff), чтобы была конкретика

2024-10-08 15:30 UTC, BeeHeather commented on MailHub.md
> +* Если пользователь находится на странице писем данной папки, то при удалении пользователь остается на той же странице
"Пользователь удаляет папку в каком угодно месте, только не на странице писем данной папки" - вот эту инфу закиньте в предыдущий кейс тогда

2024-10-08 15:30 UTC, BeeHeather commented on MailHub.md
> +* При нажатии на кнопку "Удалить ящик" всплывает плашка "Вы уверены, что хотите удалить ящик?", чтобы пользователь подтвердил действие. Если пользователь подтверждает, то удаляется профиль пользовате
Го эту проверку разделим на две отдельных - где пользователь подтверждает удаление, и где отказывается от удаления

2024-10-08 15:30 UTC, BeeHeather commented on MailHub.md
> +* Позволяет производить манипуляции с письмом
Кажется это лишняя проверка тк действия с письмом по кнопкам проверяются ниже

2024-10-08 15:30 UTC, BeeHeather commented on MailHub.md
> +* Нажатие выполняет редирект предыдущую страницу в истории, если такая есть, в противном случае редиректа не происходит
Го на два кейса разделим - где есть редирект, и где нет

2024-10-08 15:42 UTC, BeeHeather requested changes

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* Кнопка VK ID не работает, так как разработчики убрали свои данные ВК
Можете просто словами это сказать и убрать из текста

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* При вводе и отправке полей "Дата рождения", где дата имеет значение 30 февраля, отображается надпись "В этом месяце нет такого числа"
Кажется эту проверку можно не выносить отдельно и объединить с предыдущим тестом (типо проверяем верхнее граничное значение для дат)

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* При вводе и отправке полей "Дата рождения", значение которых превосходит сегодняшнее число, отображается надпись "Дата рождения превосходит сегодняшнее число"
У вас есть верхняя граница для даты рождения? (0000 год например)

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* Кнопка VK ID не работает, так как разработчики убрали свои данные ВК
Аналогично, это можно убрать

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* При вводе некорректных данных, и последующем нажатии на кнопку "Создать", пользователю выводятся ошибки
Кмк это можно убрать, каждую из возможных ошибок вы проверяете в тестах выше

2024-10-08 15:42 UTC, BeeHeather commented on MailHub.md
> +* При вводе и отправке пустого поля "Фамилия", отображается надпись "Введите фамилию"
Думаю пустые поля можно объединить в один кейс (если ошибки для каждого поля выводятся независимо)

2024-10-08 16:30 UTC, AlexKhochenkov commented on MailHub.md
> +* При вводе и отправке полей "Дата рождения", значение которых превосходит сегодняшнее число, отображается надпись "Дата рождения превосходит сегодняшнее число"
там дропбокс, нет возможности выбрать меньше 1900 года

2024-10-09 09:01 UTC, Karpov-Ivan commented on MailHub.md
> +* При нажатии на кнопку "Удалить ящик" всплывает плашка "Вы уверены, что хотите удалить ящик?", чтобы пользователь подтвердил действие. Если пользователь подтверждает, то удаляется профиль пользовате
Убрал

2024-10-09 09:01 UTC, Karpov-Ivan commented on MailHub.md
> +* Кнопка VK ID не работает, так как разработчики убрали свои данные ВК
Хорошо

2024-10-09 11:51 UTC, BeeHeather approved these changes
Аппрув

2024-10-09 12:18 UTC, merged